[package]
name = "grand_jackpot"
version = "0.1.0"
description = "5-Tier Non-Custodial Grand Jackpot with Rollover and UTC Lock on Solana"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "grand_jackpot"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.30.1"
anchor-spl = "0.30.1"
